import { PairSummary, Setup } from "../engine/types";

export const mockPairs: PairSummary[] = [
  {
    id: "BTCUSDT",
    symbol: "BTCUSDT",
    displaySymbol: "BTC/USDT",
    timeframe: "15m",
    bias: "LONG",
    setupName: "Sweep → Displacement → FVG → Retrace",
    score: 88,
    status: "WAITING",
    entry: 98200,
    sl: 97800,
    tp1: 99500,
    tp2: 100800,
    ageMinutes: 6,
    direction: "LONG",
  },
  {
    id: "ETHUSDT",
    symbol: "ETHUSDT",
    displaySymbol: "ETH/USDT",
    timeframe: "15m",
    bias: "LONG",
    setupName: "Sweep → Displacement → FVG → Retrace",
    score: 82,
    status: "TRIGGERED",
    entry: 2680,
    sl: 2644,
    tp1: 2760,
    tp2: 2835,
    ageMinutes: 12,
    direction: "LONG",
  },
  {
    id: "SOLUSDT",
    symbol: "SOLUSDT",
    displaySymbol: "SOL/USDT",
    timeframe: "15m",
    bias: "SHORT",
    setupName: "Sweep → Displacement → FVG → Retrace",
    score: 76,
    status: "WAITING",
    entry: 105.2,
    sl: 107.6,
    tp1: 99.8,
    tp2: 93.4,
    ageMinutes: 9,
    direction: "SHORT",
  },
  {
    id: "AVAXUSDT",
    symbol: "AVAXUSDT",
    displaySymbol: "AVAX/USDT",
    timeframe: "15m",
    bias: "NEUTRAL",
    setupName: "Sweep → Displacement → FVG → Retrace",
    score: 68,
    status: "WAITING",
    entry: 38.6,
    sl: 37.4,
    tp1: 41.2,
    tp2: 44.9,
    ageMinutes: 18,
    direction: "LONG",
  },
  {
    id: "XRPUSDT",
    symbol: "XRPUSDT",
    displaySymbol: "XRP/USDT",
    timeframe: "15m",
    bias: "SHORT",
    setupName: "Sweep → Displacement → FVG → Retrace",
    score: 63,
    status: "INVALIDATED",
    entry: 0.59,
    sl: 0.61,
    tp1: 0.54,
    tp2: 0.5,
    ageMinutes: 24,
    direction: "SHORT",
  },
];

export const mockSetups: Record<string, Setup> = {
  BTCUSDT: {
    id: "btc-setup",
    symbol: "BTCUSDT",
    timeframe: "15m",
    direction: "LONG",
    status: "WAITING",
    score: 88,
    createdAt: Date.now() - 6 * 60 * 1000,
    updatedAt: Date.now() - 2 * 60 * 1000,
    fvgLow: 98050,
    fvgHigh: 98450,
    sweepLevel: 97800,
    entryPrice: 98200,
    stopLoss: 97800,
    tp1: 99500,
    tp2: 100800,
    tp3: 0,
    rrToTp1: 3.2,
    invalidationText: "Invalid if 15m closes below FVG low.",
    meta: {
      bias: "LONG",
      displacementAtr: 1.05,
      freshness: "6m",
    },
  },
  SOLUSDT: {
    id: "sol-setup",
    symbol: "SOLUSDT",
    timeframe: "15m",
    direction: "SHORT",
    status: "WAITING",
    score: 76,
    createdAt: Date.now() - 9 * 60 * 1000,
    updatedAt: Date.now() - 5 * 60 * 1000,
    fvgLow: 105.8,
    fvgHigh: 107.1,
    sweepLevel: 108.4,
    entryPrice: 105.2,
    stopLoss: 107.6,
    tp1: 99.8,
    tp2: 93.4,
    tp3: 0,
    rrToTp1: 2.1,
    invalidationText: "Invalid if 15m closes above sweep high.",
    meta: {
      bias: "SHORT",
      displacementAtr: 0.92,
      freshness: "9m",
    },
  },
};
